FROM python:3.10-slim

WORKDIR /app

# Installer les dépendances système
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copier et installer les requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier les fichiers du projet
COPY . .

# Créer le dossier uploads avec permissions
RUN mkdir -p static/uploads && chmod 755 static/uploads

# Exposer le bon port
EXPOSE 5001

# Lancer l'application
CMD ["python", "app.py"]